using System;
using System.Collections.Generic;
using System.Text;

namespace Enceladus.Api
{
    [Serializable]
    public class Tractor : TractorBase
    {
        public string BauartMotor { get; set; }
        public string Kuehlung { get; set; }
        public string NenndrehzahlUmin { get; set; }
        public string Zylinderzahl { get; set; }
        public string Hubraumccm { get; set; }
        public string VerbrauchmaximalgkWh { get; set; }
        public string ECEoderISO { get; set; }
        public string BestverbrauchgkWh { get; set; }
        public string KonstantleistungProzent { get; set; }
        public string Antriebsart { get; set; }
        public string Endgeschwindigkeitkmh { get; set; }
        public string Getriebetyp { get; set; }
        public string Gaengevorwaerts { get; set; }
        public string Gaengerueckwaerts { get; set; }
        public string GetriebeWunsch { get; set; }
        public string ZW_Drehzahlen { get; set; }
        public string ZW_kW { get; set; }
        public string HubwerkKategorie { get; set; }
        public string HydraulikPumpenleistunglproMin { get; set; }
        public string HydraulikNenndruckbar { get; set; }
        public string Bereifungvorne { get; set; }
        public string Bereifunghinten { get; set; }
        public string PreisbisEuro { get; set; }
        public string Besonderes { get; set; }
        public string Ausstattung { get; set; }
        public string Pruefberichte { get; set; }
        public string Seitencodeprofi { get; set; }
        public string Seitencodetop { get; set; }
        public string Bild1 { get; set; }
        public string HerstellerMotor { get; set; }
        public string MotorTyp { get; set; }
        public string MaximalleistungkW { get; set; }
        public string MaxleistungbeiUmin { get; set; }
        public string MDmaxNm { get; set; }
        public string MDmaxbeiDrehzahl { get; set; }
        public string PmaxabUminunten { get; set; }
        public string DrehmomentanstiegProzent { get; set; }
        public string DrehzahlabfallProzent { get; set; }
        public string UberleistungkW { get; set; }
        public string BoostleistungkW { get; set; }
        public string BoostleistungbeiUmin { get; set; }
        public string BohrungxHub { get; set; }
        public string Abgasnorm { get; set; }
        public string SCRKatalysator { get; set; }
        public string Dieseloxydationskatalysator { get; set; }
        public string Dieselpartikelfilter { get; set; }
        public string Tankinhaltl { get; set; }
        public string AnzahlTanks { get; set; }
        public string Bestverbrauchlproh { get; set; }
        public string BestverbrauchbeiDrehzahl { get; set; }
        public string MittlererOECD_VerbrauchgkWh { get; set; }
        public string PowermixMittel { get; set; }
        public string AdBlueTankinhaltL { get; set; }        
        public string Getriebehersteller { get; set; }
        public string Synchronisation { get; set; }
        public string C30kmh { get; set; }
        public string C40kmh { get; set; }
        public string C50kmh { get; set; }
        public string C60kmhundmehr { get; set; }
        public string ZahlderSchalthebel { get; set; }
        public string Getriebevolllastschaltbar { get; set; }
        public string LSAnzahlStufen { get; set; }
        public string StufenlosesCVT { get; set; }
        public string Wendegetriebe { get; set; }
        public string Wendeschaltung { get; set; }
        public string WGLastschaltbar { get; set; }
        public string WGVorwahlbar { get; set; }
        public string Kriechgetriebeab { get; set; }
        public string AutomatikfunktionenGetriebe { get; set; }
        public string Gaenge4bis12kmh { get; set; }
        public string Gaengeueber15kmh { get; set; }
        public string DrehzahlreduzierteMaxGeschwindigkeit { get; set; }
        public string ZW_Uminmaximal { get; set; }
        public string ZW_Bauart { get; set; }
        public string Spar_ZW { get; set; }
        public string Weg_ZW { get; set; }
        public string ZWFernbedienung { get; set; }
        public string ZW_Stummelzahl { get; set; }
        public string ZW_Profil { get; set; }
        public string ZWlastschaltbar { get; set; }
        public string ZW_Mot_Umin_540 { get; set; }
        public string ZW_Mot_Umin_540E { get; set; }
        public string ZW_Mot_Umin_1000 { get; set; }
        public string ZW_Mot_Umin_1000E { get; set; }
        public string Front_ZWUmin { get; set; }
        public string HubkraftdurchgehenddaN { get; set; }
        public string EHR { get; set; }
        public string Zusatz_Hubzylinder { get; set; }
        public string FernbedienungimHeck { get; set; }
        public string Schnellkuppler { get; set; }
        public string Oberlenker_Regelung { get; set; }
        public string Unterlenker_Regelung { get; set; }
        public string Lageregelung { get; set; }
        public string Schwimmregelung { get; set; }
        public string Zugwiderstandsregelung { get; set; }
        public string Mischregelung { get; set; }
        public string Schlupfregelung { get; set; }
        public string FronthubwerkHubkraftdaN { get; set; }
        public string ArtHydrauliksystem { get; set; }
        public string AnzahlSteuerventile { get; set; }
        public string Abreisskupplungen { get; set; }
        public string Lenkhilfe { get; set; }
        public string HydrostatLenkung { get; set; }
        public string Lenkradverstellbar { get; set; }
        public string Radstand { get; set; }
        public string Spurweitevorne { get; set; }
        public string Spurweitehinten { get; set; }
        public string Differentialsp { get; set; }
        public string SchaltbarkeitHADiffsperre { get; set; }
        public string Allradantrieb { get; set; }
        public string VADiffsperre { get; set; }
        public string Vierradbremse { get; set; }
        public string Druckluftbremse { get; set; }
        public string VA_Federung { get; set; }
        public string Achsgewichtvorne { get; set; }
        public string Achsgewichthinten { get; set; }
        public string Gewichtsverteilung { get; set; }
        public string Achslastvorne { get; set; }
        public string Achslasthinten { get; set; }
        public string Leergewicht { get; set; }
        public string ZulGesamtgewmax { get; set; }
        public string Laenge { get; set; }
        public string Breite { get; set; }
        public string OelMotor { get; set; }
        public string OelwechselMotorStd { get; set; }
        public string Oelextern { get; set; }
        public string OelGetriebe { get; set; }
        public string OelwechselGetrStd { get; set; }
        public string OelHydraulikSerie { get; set; }
        public string OelHydraulikOption { get; set; }
        public string OelwechselHydrStd { get; set; }
        public string Kabine { get; set; }
        public string Niedrig_Kabine { get; set; }
        public string Kabinenfederung { get; set; }
        public string Lautstaerke { get; set; }
        public string Rueckfahreinrchtg { get; set; }
        public string Klima_Anlage { get; set; }
        public string ISO_Bus { get; set; }
        public string CAN_Bus { get; set; }
        public string AutomatAHK { get; set; }
        public string AHKschnellverst { get; set; }
        public string StuetzlastAHK { get; set; }
        public string Motor_Getriebe_Management { get; set; }
        public string Zugpendel { get; set; }
        public string AutoLenksystem { get; set; }
        public string Bodenfreiheit { get; set; }
        public string BedienungHeckzapfwelle { get; set; }
    }
}
